Add Basic Documentation
tum-esi/WoT-Phyng-Sim pull request #1
Opened 2023-05-27 20:50 UTC by anatolytsi

This MR will add the basic documentation for the repository and its subfolders. 

The following is added:

* Basic outline of the repository `README.md` with some information

2023-05-29 17:27 UTC, anatolytsi commented
@FadySalama initial part is done, please give feedback on added parts and would be great to hear some ideas on unfilled parts.

2023-06-07 12:26 UTC, FadySalama commented
This is really good @anatolytsi! Are you going to add something else or can I already merge this?

2023-06-07 12:47 UTC, anatolytsi commented
Thank you @FadySalama! Surely, you can merge it. If where is anything else to add - I am at your service :)

2023-06-07 13:30 UTC, FadySalama commented
Just fix the review points I listed above and I will merge it

2023-06-07 15:59 UTC, anatolytsi commented
> Just fix the review points I listed above and I will merge it

I don’t see any review points, did you upload them?

2023-06-09 13:41 UTC, FadySalama commented
I tagged you in them @anatolytsi. Can you see them now?

2023-06-09 16:59 UTC, anatolytsi commented
> I tagged you in them @anatolytsi. Can you see them now?
Not at all… Your reviews are not displayed anywhere for me. Neither in Pull Request review, nor anywhere else.

2023-06-12 09:34 UTC, FadySalama requested changes
It seems that I didn't submit my review. Here it is!

2023-06-12 09:34 UTC, FadySalama commented on README.md
> +- [Access the ParaView Server](#access-the-paraview-server)
Please make sure that indentation here is correct @anatolytsi

2023-06-12 09:34 UTC, FadySalama commented on README.md
> +## Errors and Known Problems
Errors? What errors? :P
For real though, you should write about how the simulation collapses sometimes if the parameters aren't good etc. and that you can find this out if the simulation time is not progressing @anatolytsi

2023-06-12 09:34 UTC, FadySalama commented on README.md
> +## Adding or Working on Issues
Similar to Wade, issues should have a naming convention: `[nodejs | paraview | python | misc] summarized issue description`. PRs solving issues should contain a comment saying exactly that. @anatolytsi

2023-06-12 21:16 UTC, anatolytsi commented on README.md
> +## Errors and Known Problems
No errors/problems found :D

2023-06-12 21:17 UTC, anatolytsi commented
I have pushed the changes @FadySalama, please have a look and let me know if something more has to be changed

2023-06-13 10:59 UTC, FadySalama approved these changes
Really good, will merge

2023-06-13 11:00 UTC, merged